### ISSUE TITLE
[PUN] 움직임 더 매끄럽게 동기화

### ISSUE THREAD

**Issue by semistone222** [semistone222/runner#11]
1. 호스팅 서버를 알아서 찾게끔 하면 한국이 골라지는데 대략 30ms 이하의 ping을 가진다.

2. 점프의 경우 보간을 하니 이상하게 점프하는 것처럼 보이므로 RPC로 대체 하는 것이 좋아보이기도 함.
(점프 이외에도 position과 rotation을 단순 보간해서 보여주기 때문에 실제 패드로 움직이는 것과 달라보인다고 볼 수 있다.)

3. OnPhotonSerializeView 콜백함수의 호출 간격을 sendRateOnSerialize 속성으로 설정 및 조회 할 수 있다. 이를 통해 데이터를 조금 더 촘촘하게 보내고 받을 수는 있을 것 같다.

**Comment by kugorang** [comment]
#19 에서 해결
