### ISSUE TITLE
[맵 프리팹] 지형, 기능 타일, 장애물

### ISSUE THREAD

**Issue by semistone222** [semistone222/runner#15]
지형
- [x] 타일

기능 타일
- [x] 가속도
- [x] 높은점프
- [x] 자동점프

장애물
- [ ] 넉백
- [x] 회전

**Comment by Zintaho** [comment]
회전 완료했습니다.

**Comment by Zintaho** [comment]
가속, 감속, 정지, 조이스틱 방향 전환 완료했습니다.
넉백은 현재 기술적인 문제로 보류중입니다.

**Comment by sjy9137** [comment]
현재 프로토 타입 맵 제작이 완료했습니다.

**Comment by semistone222** [comment]
#18 에서 해결
